# Generated by Django 4.2.5 on 2023-10-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categoryid',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
