# Generated by Django 4.2.5 on 2023-10-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='categoryid',
        ),
    ]
