# Generated by Django 4.2.5 on 2023-10-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_listing_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing_id',
            field=models.IntegerField(default=0),
        ),
    ]
