# Generated by Django 4.2.5 on 2023-10-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_rename_username_listing_user_username_bid_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid',
        ),
    ]
