# Generated by Django 4.2.5 on 2023-10-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_remove_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_bid',
            field=models.IntegerField(default=1),
        ),
    ]
