# Generated by Django 4.2.5 on 2023-10-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist',
            new_name='Watchlist',
        ),
    ]
