# Generated by Django 4.2.5 on 2023-10-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_rename_wishlist_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='pic_url',
            field=models.TextField(blank=True),
        ),
    ]
