# Generated by Django 4.2.5 on 2023-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='min_bid',
            new_name='current_bid',
        ),
        migrations.AddField(
            model_name='listings',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
