# Generated by Django 4.2.5 on 2023-10-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_status_listing_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pic_url',
            field=models.TextField(blank=True),
        ),
    ]
