# Generated by Django 4.2.5 on 2023-10-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comment_body_comment_user_id_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_username',
            field=models.TextField(default='None'),
        ),
    ]
