# Generated by Django 4.2.5 on 2023-10-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_comment_listing_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='username',
            new_name='user_username',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='user_username',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bid_winner',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
