# Generated by Django 4.2.5 on 2023-10-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_listing_min_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='closeBid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('user_username', models.TextField(default='None')),
                ('listing_id', models.IntegerField(default=0)),
            ],
        ),
    ]
