# Generated by Django 4.2.5 on 2023-10-16 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_bid_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('user_username', models.TextField(default='None')),
                ('listing_id', models.IntegerField(default=0)),
                ('title', models.TextField()),
            ],
        ),
    ]
